### ISSUE TITLE
Pulling in dates within a specific Matrix row

### ISSUE THREAD

**Issue by stinhambo** [expressodev/easy_icalendar#4]
Hi there,

We want to be able to pull in an event from a specific Matrix field but the output fails if we use more than three segments to pass information through. Is there any way to allow us to pass through more segments to get the right content into the ics file?

**Comment by amacneil** [comment]
Sorry not quite sure what you mean.. I can't see why segments would make any difference.

Can you perhaps post this on EESE along with a code snippet? I should see it, feel free to ping me on Twitter if I don't though.
