### ISSUE TITLE
ee281 and latest iCal

### ISSUE THREAD

**Issue by howster** [expressodev/easy_icalendar#8]
When i embed the sample code i get a pop up screen on the front end asking to download the file! See attached screenshot: [ical](https://cloud.githubusercontent.com/assets/1191091/3265085/e2454626-f289-11e3-8ff0-e4ec1d86e557.JPG)

Entire source code of my webpage turns to:

BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//ExpressionEngine Easy iCalendar plugin//NONSGML v1.2//EN
X-WR-TIMEZONE:Pacific/Auckland
END:VCALENDAR

**Comment by amacneil** [comment]
Yip, that's the point. If you want to link to it, put it in it's own template :)
